namespace RP.Math.Noise
{
    using System;

    /// <summary>
    /// Distorts <i>where</i> a noise field is sampled, rather than what comes back — the cheapest
    /// transformation in procedural generation, and the one that does the most to hide that a world was
    /// generated by an algorithm.
    /// </summary>
    /// <remarks>
    /// <para><b>The idea.</b> Instead of asking the field for its value at <c>(x, y)</c>, first ask a
    /// <i>second</i> noise field which way to nudge, then sample the first field at the nudged position.
    /// The output is the same field, but its coordinate space has been stirred.</para>
    ///
    /// <para><b>Why it matters so much.</b> Unwarped fractal noise has a characteristic look: features are
    /// blobby, they sit on invisible axes, coastlines are smooth arcs and rivers do not meander. The eye
    /// picks this up as "computer-generated" long before it can say why. Warping the domain bends those
    /// features around each other — coastlines gain fjords and peninsulas, strata fold, cave passages
    /// snake instead of running straight. One warp pass typically improves a landscape more than four extra
    /// octaves, at a fraction of the cost.</para>
    ///
    /// <para><b>Iterating.</b> Applying the warp to its own output (<see cref="Iterations"/> above 1) is
    /// the classic recursive form. Two passes give the swirling, fluid, marbled structure that reads as
    /// weathering and flow; beyond three the field becomes chaotic and loses the coherence that made it
    /// useful. Two is usually right.</para>
    ///
    /// <para>The result implements <see cref="INoise2"/> itself, so a warped field can be stacked, warped
    /// again, or dropped into anything that takes a field — the decorators compose freely.</para>
    /// </remarks>
    public sealed class DomainWarp2 : INoise2
    {
        private readonly INoise2 source;
        private readonly INoise2 warpX;
        private readonly INoise2 warpY;

        /// <summary>Wraps <paramref name="source"/> in a coordinate distortion.</summary>
        /// <param name="source">The field being sampled.</param>
        /// <param name="warpX">The field driving displacement along X.</param>
        /// <param name="warpY">The field driving displacement along Y. Must be a <i>different</i> field
        /// from <paramref name="warpX"/> (a different seed is enough) — sharing one would displace every
        /// point along the diagonal, shearing the world instead of stirring it.</param>
        /// <param name="amplitude">How far, in world units, a point may be displaced. The single most
        /// important dial: comparable to the source's feature size gives a natural fold, several times
        /// larger gives surreal tearing.</param>
        /// <param name="frequency">The scale of the distortion itself. Lower than the source's frequency
        /// bends large features; higher roughens edges without moving the shape.</param>
        /// <param name="iterations">How many times the warp is applied to its own output.</param>
        public DomainWarp2(
            INoise2 source,
            INoise2 warpX,
            INoise2 warpY,
            double amplitude = 1.0,
            double frequency = 1.0,
            int iterations = 1)
        {
            if (source == null) throw new ArgumentNullException(nameof(source));
            if (warpX == null) throw new ArgumentNullException(nameof(warpX));
            if (warpY == null) throw new ArgumentNullException(nameof(warpY));
            if (iterations < 1) throw new ArgumentOutOfRangeException(nameof(iterations), "At least one iteration is required.");

            this.source = source;
            this.warpX = warpX;
            this.warpY = warpY;
            this.Amplitude = amplitude;
            this.Frequency = frequency;
            this.Iterations = iterations;
        }

        /// <summary>How far, in world units, a sample point may be displaced.</summary>
        public double Amplitude { get; }

        /// <summary>The scale of the distortion field.</summary>
        public double Frequency { get; }

        /// <summary>How many times the warp is applied to its own output.</summary>
        public int Iterations { get; }

        /// <summary>Computes the displaced coordinate without sampling the source — useful when several
        /// fields must be warped <i>identically</i>, as height and temperature should be if their features
        /// are to stay aligned.</summary>
        public void Displace(double x, double y, out double wx, out double wy)
        {
            wx = x;
            wy = y;

            for (int i = 0; i < this.Iterations; i++)
            {
                double sx = wx * this.Frequency;
                double sy = wy * this.Frequency;
                double dx = this.warpX.Sample(sx, sy) * this.Amplitude;
                double dy = this.warpY.Sample(sx, sy) * this.Amplitude;
                wx += dx;
                wy += dy;
            }
        }

        /// <inheritdoc />
        public double Sample(double x, double y)
        {
            this.Displace(x, y, out double wx, out double wy);
            return this.source.Sample(wx, wy);
        }

        /// <summary>
        /// Builds a warp whose two displacement fields are the same kind of noise under derived seeds — the
        /// common case, saving the caller from constructing and seeding three fields by hand.
        /// </summary>
        public static DomainWarp2 Simplex(
            INoise2 source, int seed, double amplitude = 1.0, double frequency = 1.0, int iterations = 2)
        {
            return new DomainWarp2(
                source,
                new SimplexNoise(NoiseHash.Derive(seed, 0x57A1)),
                new SimplexNoise(NoiseHash.Derive(seed, 0x57A2)),
                amplitude,
                frequency,
                iterations);
        }
    }

    /// <summary>
    /// The volumetric counterpart of <see cref="DomainWarp2"/>: distorts where a 3D field is sampled.
    /// </summary>
    /// <remarks>
    /// This is what makes carved caves believable. A cave network cut straight from fractal noise has a
    /// recognisable sameness — passages of similar width meeting at similar angles. Warping the domain
    /// first stretches some passages into galleries and pinches others into crawlspaces, adds the curving
    /// switchbacks that make a system feel explored rather than generated, and costs one extra field
    /// sample per axis.
    /// </remarks>
    public sealed class DomainWarp3 : INoise3
    {
        private readonly INoise3 source;
        private readonly INoise3 warpX;
        private readonly INoise3 warpY;
        private readonly INoise3 warpZ;

        /// <summary>Wraps <paramref name="source"/> in a coordinate distortion.</summary>
        public DomainWarp3(
            INoise3 source,
            INoise3 warpX,
            INoise3 warpY,
            INoise3 warpZ,
            double amplitude = 1.0,
            double frequency = 1.0,
            int iterations = 1)
        {
            if (source == null) throw new ArgumentNullException(nameof(source));
            if (warpX == null) throw new ArgumentNullException(nameof(warpX));
            if (warpY == null) throw new ArgumentNullException(nameof(warpY));
            if (warpZ == null) throw new ArgumentNullException(nameof(warpZ));
            if (iterations < 1) throw new ArgumentOutOfRangeException(nameof(iterations), "At least one iteration is required.");

            this.source = source;
            this.warpX = warpX;
            this.warpY = warpY;
            this.warpZ = warpZ;
            this.Amplitude = amplitude;
            this.Frequency = frequency;
            this.Iterations = iterations;
        }

        /// <summary>How far, in world units, a sample point may be displaced.</summary>
        public double Amplitude { get; }

        /// <summary>The scale of the distortion field.</summary>
        public double Frequency { get; }

        /// <summary>How many times the warp is applied to its own output.</summary>
        public int Iterations { get; }

        /// <summary>Computes the displaced coordinate without sampling the source.</summary>
        public void Displace(double x, double y, double z, out double wx, out double wy, out double wz)
        {
            wx = x;
            wy = y;
            wz = z;

            for (int i = 0; i < this.Iterations; i++)
            {
                double sx = wx * this.Frequency, sy = wy * this.Frequency, sz = wz * this.Frequency;
                double dx = this.warpX.Sample(sx, sy, sz) * this.Amplitude;
                double dy = this.warpY.Sample(sx, sy, sz) * this.Amplitude;
                double dz = this.warpZ.Sample(sx, sy, sz) * this.Amplitude;
                wx += dx;
                wy += dy;
                wz += dz;
            }
        }

        /// <inheritdoc />
        public double Sample(double x, double y, double z)
        {
            this.Displace(x, y, z, out double wx, out double wy, out double wz);
            return this.source.Sample(wx, wy, wz);
        }

        /// <summary>Builds a warp whose three displacement fields are simplex noise under derived seeds.</summary>
        public static DomainWarp3 Simplex(
            INoise3 source, int seed, double amplitude = 1.0, double frequency = 1.0, int iterations = 2)
        {
            return new DomainWarp3(
                source,
                new SimplexNoise(NoiseHash.Derive(seed, 0x57B1)),
                new SimplexNoise(NoiseHash.Derive(seed, 0x57B2)),
                new SimplexNoise(NoiseHash.Derive(seed, 0x57B3)),
                amplitude,
                frequency,
                iterations);
        }
    }
}
